from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.schemas import GlossaryEntry
from app.services.prompts import DISCLAIMER

GREEN = colors.HexColor("#1b7a4e")
INK = colors.HexColor("#13261c")
GOLD = colors.HexColor("#c8961a")
CREAM = colors.HexColor("#f7f1e3")
MUTED = colors.HexColor("#5c6b62")


def build_pdf(
    original: str,
    translation: str,
    tone: str,
    glossary: list[GlossaryEntry],
    title: str = "Pidgin Law translation",
) -> bytes:
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title=title,
        author="Pidgin Law",
    )
    styles = _styles()
    story: list = [
        Paragraph("PIDGIN LAW", styles["brand"]),
        Paragraph("Legal English → Nigerian Pidgin", styles["tagline"]),
        Spacer(1, 6),
        Table(
            [[""]],
            colWidths=[document.width],
            rowHeights=[3],
        ),
        Spacer(1, 8),
        Paragraph(_escape(title), styles["heading"]),
        Paragraph(f"Tone: {_escape(tone.title())} Pidgin", styles["meta"]),
        Spacer(1, 8),
        Paragraph(_escape(DISCLAIMER), styles["disclaimer"]),
        Spacer(1, 14),
        Paragraph("Original English", styles["section"]),
        Paragraph(_nl2br(_escape(original)), styles["body"]),
        Spacer(1, 12),
        Paragraph("Pidgin translation", styles["section"]),
        Paragraph(_nl2br(_escape(translation)), styles["body"]),
    ]

    if glossary:
        story.extend(
            [
                Spacer(1, 14),
                Paragraph("Legal glossary (Pidgin explanations)", styles["section"]),
            ]
        )
        items = []
        for entry in glossary:
            block = (
                f"<b>{_escape(entry.term)}</b> — {_escape(entry.pidgin_term)}<br/>"
                f"{_escape(entry.explanation)}"
            )
            if entry.example:
                block += f"<br/><i>Example:</i> {_escape(entry.example)}"
            items.append(ListItem(Paragraph(block, styles["glossary"]), leftIndent=8))
        story.append(ListFlowable(items, bulletType="bullet", start="•", leftIndent=12))

    story.extend(
        [
            Spacer(1, 18),
            Paragraph(
                "Generated by Pidgin Law · pidginlaw · Not legal advice.",
                styles["footer"],
            ),
        ]
    )

    accent = Table([[""]], colWidths=[document.width], rowHeights=[3])
    accent.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), GREEN)]))
    story[3] = accent

    def _on_page(canvas, doc) -> None:  # noqa: ANN001
        canvas.saveState()
        canvas.setFillColor(GREEN)
        canvas.rect(0, A4[1] - 8, A4[0], 8, fill=1, stroke=0)
        canvas.setFillColor(colors.white)
        canvas.rect(0, 0, A4[0], 10, fill=1, stroke=0)
        canvas.setFillColor(GOLD)
        canvas.rect(0, 10, A4[0], 3, fill=1, stroke=0)
        canvas.setFillColor(MUTED)
        canvas.setFont("Times-Italic", 8)
        canvas.drawString(18 * mm, 6, "Pidgin Law  ·  Access to Justice")
        canvas.drawRightString(A4[0] - 18 * mm, 6, f"Page {doc.page}")
        canvas.restoreState()

    document.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    return buffer.getvalue()


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "brand": ParagraphStyle(
            "brand",
            parent=base["Heading1"],
            fontName="Times-Bold",
            fontSize=18,
            textColor=GREEN,
            spaceAfter=0,
            leading=22,
        ),
        "tagline": ParagraphStyle(
            "tagline",
            parent=base["Normal"],
            fontName="Times-Italic",
            fontSize=10,
            textColor=MUTED,
            spaceAfter=0,
        ),
        "heading": ParagraphStyle(
            "heading",
            parent=base["Heading2"],
            fontName="Times-Bold",
            fontSize=13,
            textColor=INK,
            spaceAfter=2,
        ),
        "meta": ParagraphStyle(
            "meta",
            parent=base["Normal"],
            fontSize=9,
            textColor=MUTED,
        ),
        "disclaimer": ParagraphStyle(
            "disclaimer",
            parent=base["Normal"],
            fontName="Times-Italic",
            fontSize=8.5,
            leading=12,
            textColor=INK,
            backColor=CREAM,
            borderPadding=6,
        ),
        "section": ParagraphStyle(
            "section",
            parent=base["Heading3"],
            fontName="Times-Bold",
            fontSize=11,
            textColor=GREEN,
            spaceBefore=4,
            spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "body",
            parent=base["Normal"],
            fontName="Times-Roman",
            fontSize=10,
            leading=14,
            alignment=TA_JUSTIFY,
            textColor=INK,
        ),
        "glossary": ParagraphStyle(
            "glossary",
            parent=base["Normal"],
            fontSize=9,
            leading=12.5,
            alignment=TA_LEFT,
            textColor=INK,
        ),
        "footer": ParagraphStyle(
            "footer",
            parent=base["Normal"],
            fontSize=8,
            textColor=MUTED,
            alignment=TA_LEFT,
        ),
    }


def _escape(value: str) -> str:
    return (
        (value or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _nl2br(value: str) -> str:
    return value.replace("\n\n", "<br/><br/>").replace("\n", "<br/>")
